### PR TITLE
Migrate to server_capabilities

### LINKED ISSUE #77: resolved_capabilities is deprecated for latest neovim.
Hi, thanks for the great plugin.

It seems that `resolved_capabilities` is deprecated in the latest Neovim.

You can find it here: https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767

So now I get the following message when running Neovim. Can you please address this?

image

My version of neovim is:

image

### PR DESCRIPTION
**Pull request by tomtomjhj**
resolved_capabilities is deprecated.
https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767

Fixes #77

### CODE REVIEW

**Comment by ryanburda** [comment]
I tested this and verified that the LSP warning no longer shows up. Can this be merged?

**Comment by pbogut** [comment]
Did exactly same thing in my local copy, before I found this PR. Can confirm it works fine, IMO should be merged.

**Comment by niklasmohrin** [comment]
Works as expected for me too :)

**Comment by dsummersl** [comment]
please merge 🙏 🙏 🙏 - nvim gives a deprecation warning every time a lsp supported file is loaded, very annoying!

**Comment by ryanburda** [comment]
Anyone around to merge this?

**Comment by dsummersl** [comment]
fwiw I switch to a treesitter config - https://github.com/SmiteshP/nvim-gps

**Comment by TornaxO7** [comment]
Can this be merged please?

**Review by wbthomason — APPROVED** [review]
lgtm, sorry for the delay!

**Pull request merged**
